service: pubmed-bookmarks

package:
  exclude:
    - '**'
  include:
    - src/**
    - node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  versionFunctions: false

  environment:
    stage: ${opt:stage, self:provider.stage}
    bookmarks_table: pubmed-${opt:stage, self:provider.stage}-bookmarks

  apiGateway:
    apiKeys: 
      - test-api-key-1
    usagePlan: 
      quota:
        limit: 1000
        offset: 1
        period: MONTH
      throttle: 
        burstLimit: 50
        rateLimit: 25


functions:
  ping:
    handler: src/controllers/ping.handler
    description: Ping!
    events:
    - http:
        path: /pubmed/ping
        method: get
        cors: true
        private: true
  getBookmarks:
    handler: src/controllers/bookmarks/getBookmarks.handler
    description: Get PubMed bookmarks
    events:
    - http:
        path: /pubmed/bookmarks
        method: get
        cors: true
        private: true
resources:
  Resources:
    pubmedBookmarks:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.bookmarks_table}
        AttributeDefinitions:
          - AttributeName: userPk
            AttributeType: S
          - AttributeName: articleSk
            AttributeType: S
        KeySchema:
          - AttributeName: userPk
            KeyType: HASH
          - AttributeName: articleSk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
          